font_family JetBrainsMono Nerd Font Mono

background_opacity        0.80
confirm_os_window_close   0
sync_to_monitor           no

###########################################################
# Force larger, proportional Nerd Font icons & symbols
###########################################################
symbol_map U+23FB-U+23FE,U+2B58,U+E200-U+E2A9,U+E0A0-U+E0A3,U+E0B0-U+E0BF,U+E0C0-U+E0C8,U+E0CC-U+E0CF,U+E0D0-U+E0D2,U+E0D4,U+E700-U+E7C5,U+F000-U+F2E0,U+2665,U+26A1,U+F400-U+F4A8,U+F67C,U+E000-U+E00A,U+F300-U+F372,U+E5FA-U+E6B5,U+EA60-U+EC1E,U+ED00-U+EFC1,U+F0001-U+F1AF0 Symbols Nerd Font

# Adjust symbol cell width to 2 cells for full size
narrow_symbols U+E0A0-U+E0A3,U+E0A4-U+E0C8,U+E0CC-U+E0D7,U+F000-U+F2E0 2
