general {
    lock_cmd = pidof hyprlock || hyprlock       # Prevents opening multiple instances
    before_sleep_cmd = loginctl lock-session    # Locks screen before system suspends
    after_sleep_cmd = hyprctl dispatch dpms on  # Keeps display reactive waking up
}

# Screen Saver Act 1: Lock the machine after 5 minutes
listener {
    timeout = 300                                 
    on-timeout = loginctl lock-session            
}

# Screen Saver Act 2: Turn off screen backlight 30 seconds after locking
listener {
    timeout = 330                                 
    on-timeout = hyprctl dispatch dpms off        
    on-resume = hyprctl dispatch dpms on          
}

# Screen Saver Act 3: Suspend the laptop after 10 minutes of zero activity
listener {
    timeout = 600                                 
    on-timeout = systemctl suspend                
}
